UP = (-1, 0)
DOWN = (1, 0)
LEFT = (0, -1)
RIGHT = (0, 1)
UP_RIGHT = (-1, 1)
UP_LEFT = (-1, -1)
DOWN_RIGHT = (1, 1)
DOWN_LEFT = (1, -1)

MOVES = {UP, DOWN, LEFT, RIGHT, UP_RIGHT, UP_LEFT, DOWN_RIGHT, DOWN_LEFT}

REMOVE_MAP = {
    'TOP': {UP, UP_RIGHT, UP_LEFT},
    'BOTTOM': {DOWN, DOWN_RIGHT, DOWN_LEFT},
    'LEFT': {LEFT, UP_LEFT, DOWN_LEFT},
    'RIGHT': {RIGHT, UP_RIGHT, DOWN_RIGHT},
    'TOP_LEFT': {UP, LEFT, UP_LEFT, DOWN_LEFT, UP_RIGHT},
    'TOP_RIGHT': {UP, RIGHT, UP_LEFT, DOWN_RIGHT, UP_RIGHT},
    'BOTTOM_LEFT': {DOWN, LEFT, DOWN_LEFT, UP_LEFT, DOWN_RIGHT},
    'BOTTOM_RIGHT': {DOWN, RIGHT, DOWN_LEFT, UP_RIGHT, DOWN_RIGHT},
    'ALL': set()
}

BOARD = 7
N = 1_000